#!/bin/sh
export HOME="/home/oga"
export SDL_NOMOUSE=1
# This enables audio. SPK mode does nothing on the RG-351P. (and presumbly the OGA as well)
amixer cset name='Playback Path' HP > /dev/null 2>&1;
while [ 1 ]
do
	cd $HOME
	exec ./autoexec.sh > /dev/null 2>&1;
done
